run:
  tag: VR4
  output_root: data/output
  overwrite: true

fragmentation:
  enabled: true
  input_type: csv
  input: data/input/libraries/VR4/VR4_v1_library.csv

  sequence_column: aa_sequence
  variant_id_column: gene_id
  metadata_columns:
    - criteria

  kmers:
    - 9

  variable_region:
    enabled: true
    start: 450
    end: 470
    mode: overlap

mhc:
  alleles:
    # A common internal name, followed by the format required by each tool
    - name: H2-Db
      mhcflurry: H2-D*b
      netmhcpan: H-2-Db

    - name: H2-Kb
      mhcflurry: H2-D*d
      netmhcpan: H-2-Dd

mhcflurry:
  enabled: true
  affinity_percentile_threshold: 2.0
  presentation_percentile_threshold: null
  batch_size: 100000

netmhcpan:
  enabled: true
  executable: netMHCpan
  el_rank_threshold: 2.0
  deduplicate: true

combine:
  enabled: true
  library: data/input/libraries/VR4/VR4_v1_library.csv
  variable_region_start: 450
  variable_region_end: 470
  wild_type_variable_region: TINGSGQNQQTLKFSVAGPSN

bigmhc:
  enabled: true
  model: el
  device: cpu
  threads: 2

analysis:
  enabled: false