run:
  tag: VR5_V3
  output_root: data/output
  overwrite: false

fragmentation:
  enabled: true
  input_type: csv
  input: data/input/libraries/VR5_v3_final_library_detailed.csv

  sequence_column: twist_seq_prot
  variant_id_column: Geneid
  metadata_columns:
    - criteria
    - evo_score_label
    - evo_score

  kmers:
    - 9

  variable_region:
    enabled: true
    start: 8
    end: 24
    mode: overlap

mhc:
  alleles:
    # A common internal name, followed by the format required by each tool
    - name: H2-Db
      mhcflurry: H-2-Db
      netmhcpan: H-2-Db

    - name: H2-Kb
      mhcflurry: H-2-Kb
      netmhcpan: H-2-Kb

mhcflurry:
  enabled: true
  affinity_percentile_threshold: 2.0
  presentation_percentile_threshold: null
  batch_size: 100000

netmhcpan:
  enabled: true
  executable: netMHCpan
  el_rank_threshold: 2.0
  deduplicate: true

combine:
  enabled: true
  library: data/input/libraries/VR5_v3_final_library_detailed.csv
  variable_region_start: 8
  variable_region_end: 24
  wild_type_variable_region: STTVTQNNNSEFAWPGA

bigmhc:
  enabled: true
  model: el
  device: cpu
  threads: 2
  jobs: 8

analysis:
  enabled: false