run:
  tag: WT_vr6
  output_root: data/output

fragmentation:
  enabled: true
  input_type: csv
  input: data/input/libraries/WT/AAV9_WT.csv

  sequence_column: twist_seq_prot
  variant_id_column: Geneid
  metadata_columns:
    - criteria

  kmers:
    - 9

  variable_region:
    enabled: true
    start: 526
    end: 542
    mode: overlap

mhc:
  alleles:
    # A common internal name, followed by the format required by each tool
    - name: H2-Db
      mhcflurry: H2-D*b
      netmhcpan: H-2-Db

    - name: H2-Dd
      mhcflurry: H2-D*d
      netmhcpan: H-2-Dd

    - name: H2-Kb
      mhcflurry: H2-K*b
      netmhcpan: H-2-Kb

    - name: H2-Kd
      mhcflurry: H2-K*d
      netmhcpan: H-2-Kd

    - name: H2-Ld
      mhcflurry: H2-L*d
      netmhcpan: H-2-Ld

mhcflurry:
  enabled: true
  affinity_percentile_threshold: 2.0

netmhcpan:
  enabled: true
  executable: tools/netMHCpan-4.2/netMHCpan
  el_rank_threshold: 2.0
  deduplicate: true

combine:
  enabled: true
  sequence_column: twist_seq_prot
  library_id_column: Geneid
  library: data/input/libraries/WT/AAV9_WT.csv
  variable_region_start: 526
  variable_region_end: 542
  wild_type_variable_region: SHKEGEDRFFPLSGSLI
