run:
  tag: WT_vr6
  output_root: data/output
  overwrite: true

fragmentation:
  enabled: true
  input_type: csv
  input: data/input/libraries/WT/AAV9_WT.csv

  sequence_column: twist_seq_prot
  variant_id_column: Geneid
  metadata_columns:
    - criteria

  kmers:
    - 9

  variable_region:
    enabled: true
    start: 525
    end: 542
    mode: overlap

mhc:
  alleles:
    # A common internal name, followed by the format required by each tool
    - name: H2-Db
      mhcflurry: H2-D*b
      netmhcpan: H-2-Db

    - name: H2-Kb
      mhcflurry: H2-D*d
      netmhcpan: H-2-Dd

mhcflurry:
  enabled: true
  affinity_percentile_threshold: 2.0
  presentation_percentile_threshold: null
  batch_size: 100000

netmhcpan:
  enabled: true
  executable: netMHCpan
  el_rank_threshold: 2.0
  deduplicate: true

combine:
  enabled: true
  sequence_column: twist_seq_prot
  library_id_column: Geneid
  library: data/input/libraries/WT/AAV9_WT.csv
  variable_region_start: 525
  variable_region_end: 542
  wild_type_variable_region: TINGSGQNQQTLKFSVAGPSN

bigmhc:
  enabled: true
  model: el
  device: cpu
  threads: 2

analysis:
  enabled: false
