# Allele-specific delta-only tissue expression analysis
#
# Purpose
# -------
# Analyse whether WT-relative immunogenicity delta scores are associated
# with tissue expression for a single allele-specific variant score table.
#
# Keeps only:
#   1. Correlations between tissue expression and delta features
#   2. Linear regression: y ~ delta_score
#   3. Linear regression adjusted for mutation count: y ~ delta_score + mutation_count
#   4. Coefficient forest plots similar to the previous script
#
# Explicitly removes:
#   - Reverse count models
#   - Epitope count category models
#   - Top/bottom decile comparisons
#   - Non-delta absolute score modelling
#
# Expected inputs
# ---------------
# Tissue file:
#   CSV with columns:
#       gene_id  -> variant_id
#       y        -> tissue expression / relative enrichment score
#
# Immunogenicity file:
#   Allele-specific variant_immunogenicity_scores.tsv generated by the
#   WT-relative scoring script. One row per variant for one allele.

from __future__ import annotations

from pathlib import Path
import re

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import pearsonr, spearmanr
import statsmodels.api as sm


# ------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------

TISSUE_FILE = Path(
    "data/input/expression/VR6/TIS00005_kidney_relative_to_virus_fold_1.csv"
)

IMMUNOGENICITY_FILE = Path(
    "data/output/variant_immunogenicity_scores_wt/VR6_K9_H2-Db/"
    "variant_immunogenicity_scores.tsv"
)

OUTPUT_DIR = Path(
    "data/output/tissue_expression_analysis_wt/VR6_K9_H2-Db/kidney"
)

# If True, also create log2(y) when y values are positive.
# The default model outcome remains y unless OUTCOME_COLUMN is changed below.
CREATE_LOG2_Y = True
OUTCOME_COLUMN = "y"

# Robust standard errors for OLS.
OLS_COV_TYPE = "HC3"


# ------------------------------------------------------------------
# Output directories
# ------------------------------------------------------------------

TABLE_DIR = OUTPUT_DIR / "tables"
PLOT_DIR = OUTPUT_DIR / "plots"
SCATTER_DIR = PLOT_DIR / "delta_scatter_plots"
FOREST_DIR = PLOT_DIR / "delta_regression_forest_plots"
DISTRIBUTION_DIR = PLOT_DIR / "distributions"

for directory in [
    OUTPUT_DIR,
    TABLE_DIR,
    PLOT_DIR,
    SCATTER_DIR,
    FOREST_DIR,
    DISTRIBUTION_DIR,
]:
    directory.mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------------
# Helper functions
# ------------------------------------------------------------------

def safe_filename(name: str) -> str:
    """Convert a column name into a safe filename stem."""
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(name)).strip("_")


def numeric_series(df: pd.DataFrame, column: str) -> pd.Series:
    """Return a numeric version of a dataframe column."""
    return pd.to_numeric(df[column], errors="coerce")


def require_columns(df: pd.DataFrame, columns: list[str], source_name: str) -> None:
    """Raise a clear error if required columns are missing."""
    missing = [column for column in columns if column not in df.columns]
    if missing:
        raise ValueError(
            f"{source_name} is missing required columns: "
            + ", ".join(missing)
        )


def is_delta_column(column: str) -> bool:
    """
    Identify WT-relative delta features only.

    Included examples:
        netMHCpan_top_delta_vs_WT
        netMHCpan_mean_top3_delta_vs_WT
        MHCflurry_top_delta_vs_WT
        BigMHC_top_delta_vs_WT
        netMHCpan_net_pass_change
        both_net_pass_change

    Excluded examples:
        netMHCpan_passed_count
        netMHCpan_new_passed_count
        netMHCpan_lost_passed_count
        netMHCpan_top_score
    """
    lower = column.lower()

    if "delta_vs_wt" in lower:
        return True

    if lower.endswith("net_pass_change"):
        return True

    return False


def pretty_label(column: str) -> str:
    """Human-readable labels for plots."""
    labels = {
        "netMHCpan_net_pass_change": "NetMHCpan net pass change",
        "MHCflurry_net_pass_change": "MHCflurry net pass change",
        "both_net_pass_change": "Both tools net pass change",
        "either_net_pass_change": "Either tool net pass change",
        "netMHCpan_top_delta_vs_WT": "NetMHCpan strongest delta vs WT",
        "netMHCpan_mean_top3_delta_vs_WT": "NetMHCpan mean top 3 delta vs WT",
        "netMHCpan_mean_delta_vs_WT": "NetMHCpan mean delta vs WT",
        "MHCflurry_top_delta_vs_WT": "MHCflurry strongest delta vs WT",
        "MHCflurry_mean_top3_delta_vs_WT": "MHCflurry mean top 3 delta vs WT",
        "MHCflurry_mean_delta_vs_WT": "MHCflurry mean delta vs WT",
        "BigMHC_top_delta_vs_WT": "BigMHC strongest delta vs WT",
        "BigMHC_mean_top3_delta_vs_WT": "BigMHC mean top 3 delta vs WT",
        "BigMHC_mean_delta_vs_WT": "BigMHC mean delta vs WT",
    }

    return labels.get(column, column.replace("_", " "))


def feature_family(column: str) -> str:
    """Group delta features into count, NetMHCpan, MHCflurry, BigMHC, or other."""
    lower = column.lower()

    if lower.endswith("net_pass_change"):
        return "delta_pass_counts"

    if lower.startswith("netmhcpan"):
        return "netmhcpan_delta_scores"

    if lower.startswith("mhcflurry"):
        return "mhcflurry_delta_scores"

    if lower.startswith("bigmhc"):
        return "bigmhc_delta_scores"

    return "other_delta_scores"


def delta_direction_note(column: str) -> str:
    """Interpretation note for coefficient direction."""
    lower = column.lower()

    if lower.endswith("net_pass_change"):
        return (
            "Positive values mean the variant gained more passing epitopes "
            "than it lost relative to WT."
        )

    if lower.startswith("bigmhc"):
        return (
            "Positive delta means higher BigMHC score than matched WT "
            "and therefore higher predicted immunogenicity."
        )

    if lower.startswith("netmhcpan") or lower.startswith("mhcflurry"):
        return (
            "Negative delta means a lower rank/percentile than matched WT, "
            "therefore stronger predicted presentation than WT."
        )

    return "WT-relative delta feature."


# ------------------------------------------------------------------
# Load tissue-expression data
# ------------------------------------------------------------------

print(f"Reading tissue-expression data from: {TISSUE_FILE}")

tissue_df = pd.read_csv(TISSUE_FILE)
require_columns(tissue_df, ["gene_id", "y"], "Tissue-expression file")

tissue_df["gene_id"] = tissue_df["gene_id"].astype(str).str.strip()
tissue_df["y"] = pd.to_numeric(tissue_df["y"], errors="coerce")

tissue_df = tissue_df.dropna(subset=["gene_id", "y"]).copy()

# Check one expression value per variant.
y_counts = tissue_df.groupby("gene_id", observed=True)["y"].nunique()
conflicting_variants = y_counts[y_counts > 1]

if not conflicting_variants.empty:
    raise ValueError(
        f"{len(conflicting_variants)} variants have more than one unique y value. "
        "Filter the tissue file to one endpoint/source before running this script."
    )

tissue_variant_df = (
    tissue_df[["gene_id", "y"]]
    .drop_duplicates(subset=["gene_id"])
    .rename(columns={"gene_id": "variant_id"})
)

if CREATE_LOG2_Y:
    if (tissue_variant_df["y"] > 0).all():
        tissue_variant_df["log2_y"] = np.log2(tissue_variant_df["y"])
    else:
        print(
            "Skipping log2_y creation because at least one y value is <= 0."
        )

if OUTCOME_COLUMN not in tissue_variant_df.columns:
    raise ValueError(
        f"OUTCOME_COLUMN='{OUTCOME_COLUMN}' was not found after loading tissue data."
    )

print(
    f"Unique variants with tissue expression: "
    f"{tissue_variant_df['variant_id'].nunique():,}"
)


# ------------------------------------------------------------------
# Load allele-specific immunogenicity scores
# ------------------------------------------------------------------

print(f"Reading allele-specific immunogenicity scores from: {IMMUNOGENICITY_FILE}")

scores_df = pd.read_csv(IMMUNOGENICITY_FILE, sep="\t", low_memory=False)
require_columns(scores_df, ["variant_id"], "Immunogenicity score file")

scores_df["variant_id"] = scores_df["variant_id"].astype(str).str.strip()

if "allele" in scores_df.columns and scores_df["allele"].nunique(dropna=True) > 1:
    raise ValueError(
        "This script expects one allele-specific immunogenicity table. "
        "The provided file contains multiple alleles. Use one allele-specific output directory."
    )

if scores_df["variant_id"].duplicated().any():
    duplicate_count = scores_df.loc[
        scores_df["variant_id"].duplicated(keep=False),
        "variant_id",
    ].nunique()

    raise ValueError(
        f"The immunogenicity file contains {duplicate_count} duplicated variant IDs. "
        "Use an allele-specific score table with one row per variant."
    )


# ------------------------------------------------------------------
# Identify delta columns
# ------------------------------------------------------------------

delta_columns = [
    column
    for column in scores_df.columns
    if is_delta_column(column)
]

# Keep only numeric delta columns with variation after coercion.
valid_delta_columns = []
for column in delta_columns:
    numeric_values = pd.to_numeric(scores_df[column], errors="coerce")
    if numeric_values.notna().sum() >= 3 and numeric_values.nunique(dropna=True) >= 2:
        valid_delta_columns.append(column)

if not valid_delta_columns:
    raise ValueError(
        "No usable delta columns were found. Expected columns containing "
        "'delta_vs_WT' or ending in 'net_pass_change'."
    )

print("\nDelta columns selected for modelling:")
for column in valid_delta_columns:
    print(f"  {column}")


# ------------------------------------------------------------------
# Merge tissue expression and immunogenicity scores
# ------------------------------------------------------------------

analysis_columns = ["variant_id"] + valid_delta_columns

if "mutation_count" in scores_df.columns:
    analysis_columns.append("mutation_count")

if "VR_mutation" in scores_df.columns:
    analysis_columns.append("VR_mutation")

if "allele" in scores_df.columns:
    analysis_columns.append("allele")

analysis_df = tissue_variant_df.merge(
    scores_df[analysis_columns],
    on="variant_id",
    how="inner",
    validate="one_to_one",
)

for column in valid_delta_columns:
    analysis_df[column] = pd.to_numeric(analysis_df[column], errors="coerce")

if "mutation_count" in analysis_df.columns:
    analysis_df["mutation_count"] = pd.to_numeric(
        analysis_df["mutation_count"],
        errors="coerce",
    )

n_tissue = tissue_variant_df["variant_id"].nunique()
n_scores = scores_df["variant_id"].nunique()
n_matched = analysis_df["variant_id"].nunique()

summary_df = pd.DataFrame(
    [
        {
            "tissue_file": str(TISSUE_FILE),
            "immunogenicity_file": str(IMMUNOGENICITY_FILE),
            "output_dir": str(OUTPUT_DIR),
            "outcome_column": OUTCOME_COLUMN,
            "n_tissue_variants": n_tissue,
            "n_score_variants": n_scores,
            "n_matched_variants": n_matched,
            "tissue_variants_without_scores": n_tissue - n_matched,
            "score_variants_without_tissue": n_scores - n_matched,
            "percent_tissue_variants_matched": 100 * n_matched / n_tissue if n_tissue else np.nan,
            "n_delta_features_modelled": len(valid_delta_columns),
            "ols_cov_type": OLS_COV_TYPE,
        }
    ]
)

summary_df.to_csv(
    TABLE_DIR / "analysis_input_summary.tsv",
    sep="\t",
    index=False,
)

analysis_df.to_csv(
    TABLE_DIR / "tissue_expression_delta_merged.tsv",
    sep="\t",
    index=False,
)

print(f"\nVariants in tissue dataframe:         {n_tissue:,}")
print(f"Variants in immunogenicity dataframe: {n_scores:,}")
print(f"Variants matched between dataframes:  {n_matched:,}")
print(f"Tissue variants without scores:       {n_tissue - n_matched:,}")
print(
    f"Percentage of tissue variants matched: "
    f"{100 * n_matched / n_tissue:.2f}%"
)


# ------------------------------------------------------------------
# Outcome distribution plot
# ------------------------------------------------------------------

outcome_values = analysis_df[OUTCOME_COLUMN].dropna()

plt.figure(figsize=(8, 5))
plt.hist(outcome_values, bins=40, edgecolor="black")
plt.axvline(
    outcome_values.median(),
    linestyle="--",
    label=f"Median = {outcome_values.median():.3g}",
)
plt.xlabel(OUTCOME_COLUMN)
plt.ylabel("Number of variants")
plt.title(f"Distribution of {OUTCOME_COLUMN}")
plt.legend()
plt.tight_layout()
plt.savefig(
    DISTRIBUTION_DIR / f"{safe_filename(OUTCOME_COLUMN)}_distribution.png",
    dpi=300,
    bbox_inches="tight",
)
plt.close()


# ------------------------------------------------------------------
# Correlations and scatter plots
# ------------------------------------------------------------------

correlation_results = []

for score_column in valid_delta_columns:
    correlation_data = analysis_df[["variant_id", OUTCOME_COLUMN, score_column]].copy()
    correlation_data[OUTCOME_COLUMN] = pd.to_numeric(
        correlation_data[OUTCOME_COLUMN],
        errors="coerce",
    )
    correlation_data[score_column] = pd.to_numeric(
        correlation_data[score_column],
        errors="coerce",
    )
    correlation_data = correlation_data.dropna(subset=[OUTCOME_COLUMN, score_column])

    n_complete = len(correlation_data)
    n_unique_score_values = correlation_data[score_column].nunique()
    n_unique_y_values = correlation_data[OUTCOME_COLUMN].nunique()

    if n_complete < 3 or n_unique_score_values < 2 or n_unique_y_values < 2:
        pearson_r = np.nan
        pearson_p = np.nan
        spearman_rho = np.nan
        spearman_p = np.nan
    else:
        pearson_result = pearsonr(
            correlation_data[score_column],
            correlation_data[OUTCOME_COLUMN],
        )
        spearman_result = spearmanr(
            correlation_data[score_column],
            correlation_data[OUTCOME_COLUMN],
        )

        pearson_r = pearson_result.statistic
        pearson_p = pearson_result.pvalue
        spearman_rho = spearman_result.statistic
        spearman_p = spearman_result.pvalue

    correlation_results.append(
        {
            "score": score_column,
            "score_label": pretty_label(score_column),
            "feature_family": feature_family(score_column),
            "outcome": OUTCOME_COLUMN,
            "n_variants": n_complete,
            "n_missing": len(analysis_df) - n_complete,
            "n_unique_score_values": n_unique_score_values,
            "pearson_r": pearson_r,
            "pearson_p_value": pearson_p,
            "spearman_rho": spearman_rho,
            "spearman_p_value": spearman_p,
            "direction_note": delta_direction_note(score_column),
        }
    )

    if n_complete > 0:
        plt.figure(figsize=(7, 5))
        plt.scatter(
            correlation_data[score_column],
            correlation_data[OUTCOME_COLUMN],
            alpha=0.5,
        )
        plt.xlabel(pretty_label(score_column))
        plt.ylabel(OUTCOME_COLUMN)
        plt.title(f"{pretty_label(score_column)} vs {OUTCOME_COLUMN}")

        annotation = (
            f"n = {n_complete:,}\n"
            f"Pearson r = {pearson_r:.3f}\n"
            f"Spearman ρ = {spearman_rho:.3f}"
        )
        plt.text(
            0.05,
            0.95,
            annotation,
            transform=plt.gca().transAxes,
            verticalalignment="top",
            bbox={
                "boxstyle": "round",
                "facecolor": "white",
                "alpha": 0.8,
            },
        )
        plt.tight_layout()
        plt.savefig(
            SCATTER_DIR / f"{safe_filename(score_column)}_vs_{safe_filename(OUTCOME_COLUMN)}.png",
            dpi=300,
            bbox_inches="tight",
        )
        plt.close()

correlation_df = pd.DataFrame(correlation_results)
correlation_df = correlation_df.sort_values(
    "spearman_rho",
    key=lambda values: values.abs(),
    ascending=False,
)

correlation_df.to_csv(
    TABLE_DIR / "delta_expression_correlations.tsv",
    sep="\t",
    index=False,
)

print("\nDelta correlation results:")
print(
    correlation_df[
        [
            "score",
            "n_variants",
            "pearson_r",
            "pearson_p_value",
            "spearman_rho",
            "spearman_p_value",
        ]
    ].to_string(index=False)
)


# ------------------------------------------------------------------
# Linear regression: y ~ delta_score, with optional mutation adjustment
# ------------------------------------------------------------------

def fit_ols_model(
    data: pd.DataFrame,
    outcome: str,
    predictor: str,
    adjust_for_mutations: bool,
) -> dict | None:
    """Fit OLS model with robust standard errors."""
    model_columns = [outcome, predictor]

    if adjust_for_mutations:
        if "mutation_count" not in data.columns:
            return None
        model_columns.append("mutation_count")

    model_data = data[model_columns].copy()

    for column in model_columns:
        model_data[column] = pd.to_numeric(model_data[column], errors="coerce")

    model_data = model_data.dropna()

    if len(model_data) < 3:
        print(f"Skipping {predictor}: fewer than 3 complete observations.")
        return None

    if model_data[predictor].nunique() < 2:
        print(f"Skipping {predictor}: fewer than 2 unique predictor values.")
        return None

    predictors = [predictor]
    if adjust_for_mutations:
        if model_data["mutation_count"].nunique() < 2:
            print(
                f"Skipping adjusted model for {predictor}: "
                "mutation_count has fewer than 2 unique values."
            )
            return None
        predictors.append("mutation_count")

    X = sm.add_constant(model_data[predictors], has_constant="add")
    y = model_data[outcome]

    model = sm.OLS(y, X).fit(cov_type=OLS_COV_TYPE)
    ci = model.conf_int().loc[predictor]

    result = {
        "score": predictor,
        "score_label": pretty_label(predictor),
        "feature_family": feature_family(predictor),
        "outcome": outcome,
        "model": "adjusted_for_mutation_count" if adjust_for_mutations else "unadjusted",
        "n_variants": int(model.nobs),
        "coefficient": model.params[predictor],
        "robust_std_error": model.bse[predictor],
        "t_value": model.tvalues[predictor],
        "p_value": model.pvalues[predictor],
        "ci_lower": ci.iloc[0],
        "ci_upper": ci.iloc[1],
        "intercept": model.params["const"],
        "r_squared": model.rsquared,
        "adjusted_r_squared": model.rsquared_adj,
        "aic": model.aic,
        "bic": model.bic,
        "direction_note": delta_direction_note(predictor),
    }

    if adjust_for_mutations:
        result["mutation_count_coefficient"] = model.params.get("mutation_count", np.nan)
        result["mutation_count_p_value"] = model.pvalues.get("mutation_count", np.nan)
    else:
        result["mutation_count_coefficient"] = np.nan
        result["mutation_count_p_value"] = np.nan

    return result


regression_results = []

for score_column in valid_delta_columns:
    for adjust_for_mutations in [False, True]:
        result = fit_ols_model(
            data=analysis_df,
            outcome=OUTCOME_COLUMN,
            predictor=score_column,
            adjust_for_mutations=adjust_for_mutations,
        )

        if result is not None:
            regression_results.append(result)

regression_df = pd.DataFrame(regression_results)

if regression_df.empty:
    raise ValueError("No linear regression models could be fitted.")

regression_df = regression_df.sort_values(
    ["feature_family", "score", "model"]
).reset_index(drop=True)

regression_df.to_csv(
    TABLE_DIR / "delta_expression_linear_regression.tsv",
    sep="\t",
    index=False,
)

print("\nDelta linear regression results:")
print(
    regression_df[
        [
            "score",
            "model",
            "n_variants",
            "coefficient",
            "ci_lower",
            "ci_upper",
            "p_value",
            "r_squared",
        ]
    ].to_string(index=False)
)


# ------------------------------------------------------------------
# Adjusted vs unadjusted comparison
# ------------------------------------------------------------------

comparison_df = regression_df.pivot_table(
    index=["score", "score_label", "feature_family", "outcome"],
    columns="model",
    values=[
        "n_variants",
        "coefficient",
        "robust_std_error",
        "p_value",
        "ci_lower",
        "ci_upper",
        "r_squared",
        "adjusted_r_squared",
    ],
    aggfunc="first",
)

comparison_df.columns = [
    f"{statistic}_{model_name}"
    for statistic, model_name in comparison_df.columns
]

comparison_df = comparison_df.reset_index()

if (
    "coefficient_adjusted_for_mutation_count" in comparison_df.columns
    and "coefficient_unadjusted" in comparison_df.columns
):
    comparison_df["coefficient_change_after_adjustment"] = (
        comparison_df["coefficient_adjusted_for_mutation_count"]
        - comparison_df["coefficient_unadjusted"]
    )

    comparison_df["percent_coefficient_change"] = np.where(
        comparison_df["coefficient_unadjusted"].ne(0),
        comparison_df["coefficient_change_after_adjustment"]
        / comparison_df["coefficient_unadjusted"].abs()
        * 100,
        np.nan,
    )

comparison_df.to_csv(
    TABLE_DIR / "delta_regression_adjusted_vs_unadjusted.tsv",
    sep="\t",
    index=False,
)


# ------------------------------------------------------------------
# Forest plots
# ------------------------------------------------------------------

MODEL_LABELS = {
    "unadjusted": "Unadjusted",
    "adjusted_for_mutation_count": "Adjusted for mutation count",
}


def create_forest_plot(
    results_df: pd.DataFrame,
    features: list[str],
    title: str,
    output_file: Path,
) -> None:
    """Create forest plot for selected delta features."""
    plot_df = results_df.loc[
        results_df["score"].isin(features)
        & results_df["model"].isin(MODEL_LABELS)
    ].copy()

    if plot_df.empty:
        print(f"No regression rows available for forest plot: {title}")
        return

    feature_order = [
        feature
        for feature in features
        if feature in plot_df["score"].unique()
    ]

    base_positions = {
        feature: len(feature_order) - 1 - index
        for index, feature in enumerate(feature_order)
    }

    model_offsets = {
        "unadjusted": 0.12,
        "adjusted_for_mutation_count": -0.12,
    }

    model_markers = {
        "unadjusted": "o",
        "adjusted_for_mutation_count": "s",
    }

    fig, ax = plt.subplots(figsize=(10, max(4.5, len(feature_order) * 1.1)))

    for model_name in ["unadjusted", "adjusted_for_mutation_count"]:
        model_df = plot_df.loc[plot_df["model"] == model_name].copy()

        if model_df.empty:
            continue

        model_df["feature_order"] = model_df["score"].map(
            {feature: index for index, feature in enumerate(feature_order)}
        )
        model_df = model_df.sort_values("feature_order")

        y_positions = [
            base_positions[score] + model_offsets[model_name]
            for score in model_df["score"]
        ]

        lower_errors = model_df["coefficient"] - model_df["ci_lower"]
        upper_errors = model_df["ci_upper"] - model_df["coefficient"]

        ax.errorbar(
            model_df["coefficient"],
            y_positions,
            xerr=np.vstack([lower_errors, upper_errors]),
            fmt=model_markers[model_name],
            capsize=4,
            markersize=7,
            linewidth=1.5,
            label=MODEL_LABELS[model_name],
        )

    ax.axvline(0, linestyle="--", linewidth=1)

    y_ticks = [base_positions[feature] for feature in feature_order]
    y_labels = [pretty_label(feature) for feature in feature_order]

    ax.set_yticks(y_ticks)
    ax.set_yticklabels(y_labels)
    ax.set_xlabel(f"Regression coefficient for {OUTCOME_COLUMN} (95% CI)")
    ax.set_title(title)
    ax.grid(axis="x", linestyle=":", alpha=0.4)
    ax.legend(title="Model", frameon=False, loc="best")

    fig.tight_layout()
    fig.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.close(fig)


# One forest plot for all delta features.
create_forest_plot(
    results_df=regression_df,
    features=valid_delta_columns,
    title="Association between WT-relative delta scores and tissue expression",
    output_file=FOREST_DIR / "all_delta_features_regression_forest_plot.png",
)

# Separate cleaner plots by feature family.
for family, family_df in regression_df.groupby("feature_family", observed=True):
    family_features = [
        feature
        for feature in valid_delta_columns
        if feature_family(feature) == family
    ]

    create_forest_plot(
        results_df=regression_df,
        features=family_features,
        title=f"{family.replace('_', ' ').title()} vs tissue expression",
        output_file=FOREST_DIR / f"{safe_filename(family)}_regression_forest_plot.png",
    )


# ------------------------------------------------------------------
# Manifest
# ------------------------------------------------------------------

manifest_rows = [
    {
        "file": str(TABLE_DIR / "analysis_input_summary.tsv"),
        "description": "Input paths, merge counts, outcome column, and number of delta features modelled.",
    },
    {
        "file": str(TABLE_DIR / "tissue_expression_delta_merged.tsv"),
        "description": "Merged tissue-expression and allele-specific delta score table used for analysis.",
    },
    {
        "file": str(TABLE_DIR / "delta_expression_correlations.tsv"),
        "description": "Pearson and Spearman correlations between each delta feature and tissue expression.",
    },
    {
        "file": str(TABLE_DIR / "delta_expression_linear_regression.tsv"),
        "description": "OLS models for tissue expression predicted by each delta feature, unadjusted and mutation-count-adjusted.",
    },
    {
        "file": str(TABLE_DIR / "delta_regression_adjusted_vs_unadjusted.tsv"),
        "description": "Side-by-side adjusted and unadjusted delta coefficient comparison.",
    },
    {
        "file": str(FOREST_DIR / "all_delta_features_regression_forest_plot.png"),
        "description": "Forest plot of all delta-feature coefficients.",
    },
]

for family in sorted(regression_df["feature_family"].dropna().unique()):
    manifest_rows.append(
        {
            "file": str(FOREST_DIR / f"{safe_filename(family)}_regression_forest_plot.png"),
            "description": f"Forest plot for {family} features.",
        }
    )

pd.DataFrame(manifest_rows).to_csv(
    OUTPUT_DIR / "OUTPUT_MANIFEST.tsv",
    sep="\t",
    index=False,
)

print("\nKey outputs written to:")
print(f"  {TABLE_DIR / 'delta_expression_correlations.tsv'}")
print(f"  {TABLE_DIR / 'delta_expression_linear_regression.tsv'}")
print(f"  {TABLE_DIR / 'delta_regression_adjusted_vs_unadjusted.tsv'}")
print(f"  {FOREST_DIR / 'all_delta_features_regression_forest_plot.png'}")
print(f"  {OUTPUT_DIR / 'OUTPUT_MANIFEST.tsv'}")

